### ISSUE TITLE
Couldn't open in Android Studio

### ISSUE THREAD

**Issue by ShahnazK** [universum-studios/android_transitions#11]
i downloaded transitions zip and trying to open in AS but couldn't able to do that. Getting following errors -`Error:Illegal null value provided in this collection: [-l, Java, -r, E:\android_transitions-master\library\build/reports/coverage/debug/report.xml, --projectToken, null]`

can you please help to solve this?

**Comment by albedinsky** [comment]
Hi there, I might know where the issue is, just give me a minute and I will look at it.

**Comment by albedinsky** [comment]
Could you please try to download source code as **zip** for the [issue/#11](https://github.com/universum-studios/android_transitions/tree/issue/%2311) branch and see if the issue has been fixed?

**Comment by ShahnazK** [comment]
Hi Martin, 
You rock!!! it is working for me. Thanks for super sonic response.

**Comment by albedinsky** [comment]
Thanks for reporting the issue and I am glad that we were able to resolve it.
